image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
skip_tags: false
skip_commits:
  files:
    - '**/*.md'

environment:
  Appveyor: true

services:
init:
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

build_script:
  - ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -RunTests

test: off
artifacts:
  - path: .\.nupkgs\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/sqlkata/api/v2/package
  on:
    branch:
      - master
  api_key:
    secure: /hqoLdVFa9YcKAGHHsOfe43vAfVU1hPNpUyG+Qd9PQZIAOli32cBXYTP6vq12xKq

- provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: vjMzLgB/79JfN2E9TLXdRpnshxSrVKVlo6CH/w4uDQje05dwzcPZLtnMVp0dNWBb
